matrix:
  include:
    - language: node_js
      node_js:
        - 13
      cache:
        directories:
          - node_modules
      before_install:
        - cd client
    - language: elixir
      elixir:
        - '1.10.2'
      before_install:
        - cd server
