matrix:
  include:
    language: node_js
    node_js:
      - 13
    cache:
      directories:
        - node_modules
    before_install:
      - cd client
    install:
      - npm install
    before_script:
      - cd client
    script:
      - npm test
